### ISSUE TITLE
Generated Playlist View

### ISSUE THREAD

**Issue by sharvanijha** [cs130-w21/18#29]
## User Story
As a **user**, I would like **to view a playlist once it is generated** so that **I can see what contents the playlist holds without having to switch to the Spotify app (thus reducing context switching)**.

## Detailed Description
Once a playlist has been created (either through the slider method or through the use of a mood (and thus its associated parameters), it ought to be displayed to the user on the page. The view of the generated playlist should include:
- [ ] An embedded view of the Spotify playlist
- [ ] Display of the associated mood (if there is one) that this playlist was generated from

## Acceptance Criteria
- [ ] Given **that a playlist has successfully been generated**, then **I can see this playlist and its associated tracks on the webpage**
- [ ] Given **this playlist was generated from a mood**, then **the mood this playlist was generated from is displayed on the page as well**

**Comment by willob99** [comment]
Same as #56
